config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get 'page/:page', action: :index, on: :collection
  end

  resources :books, concerns: [:paginatable] do
    resources :book_allocations, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    get :logout, on: :collection
  end

  root to: 'books#index'
end

app/models/book_allocation.rb
class BookAllocation
  include ActiveModel::Model

  attr_accessor :book_id, :consumer_email

  validates :book_id, :consumer_email, presence: true
  validate  :valid_consumer?
  validate  :duplicate_allocation

  def initialize(attrs = {})
    @book_id        = attrs[:book_id]
    @consumer_email = attrs[:consumer_email]
  end

  def create
    return unless self.valid?

    consumer.book_issues.create(book_id: book_id, issued_at: DateTime.current)
    Book.increment_counter(:available_copies, 1)

    true
  end

  private

  def consumer
    @consumer ||= Consumer.where(email: consumer_email).first
  end

  def consumer_exists?
    !!consumer
  end

  def valid_consumer?
    return if consumer_exists?

    self.errors.add(:consumer_email, I18n.t('book.allocations.invalid_user'))
  end

  def duplicate_allocation
    return unless consumer_exists?
    return if !consumer.book_issues.where(book_id: book_id).exists?

    self.errors.add(:base, I18n.t('book.allocations.duplicate'))
  end
end

app/controllers/book_allocations_controller.rb
class BookAllocationsController < ApplicationController
  before_action :authenticate

  def new
    @book            = Book.find(params[:book_id])
    @book_allocation = BookAllocation.new

    authorize @book_allocation
  end

  def create
    @book            = Book.find(params[:book_id])
    @book_allocation = BookAllocation.new(book_id: @book.id,
                                          consumer_email: book_allocation_params[:consumer_email])

    authorize @book_allocation

    if @book_allocation.create
      redirect_to book_url(@book), notice: 'Book allocation successful'
    else
      render :new
    end
  end

  private

  def book_allocation_params
    params.require(:book_allocation).permit(:consumer_email)
  end
end

app/views/book_allocations/new.html.erb
<% select_nav 'Books' %>

<div id='page_content'>
  <div class='page-header'>
    <h2>
      New Book Allocation - <%= @book.title %>
    </h2>
  </div>

  <div class='page-body'>
    <%= form_for @book_allocation, url: book_book_allocations_url(@book), html: {class: 'form-horizontal'} do |f| %>

      <% if f.object.errors[:base].present? %>
        <%= render_flash_message(:alert, f.object.errors[:base].join('\n')) %>
      <% end %>

      <div class='form-group <%= error_class_for(f.object, :consumer_email) %>'>
        <%= f.label :consumer_email, class: 'col-sm-2 control-label' %>
        <div class='col-sm-4'>
          <%= f.text_field :consumer_email, class: 'form-control', placeholder: 'Enter Consumer Email' %>
          <%= error_messages_for(f.object, :consumer_email) %>
        </div>
      </div>

      <div class='form-group'>
        <div class='col-sm-offset-2 col-sm-4'>
          <%= f.submit 'Create', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>