config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get 'page/:page', action: :index, on: :collection
  end

  resources :books, concerns: [:paginatable] do
    resources :book_allocations, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    get :logout, on: :collection
  end

  root to: 'books#index'
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, :author, presence: true
  validates :isbn, presence: true, uniqueness: { case_sensitive: false }
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  has_many :book_issues

  before_save :upcase_isbn

  def availability
    self.quantity - self.available_copies
  end

  private

  def upcase_isbn
    self.isbn = self.isbn.upcase
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate

  def index
    @books = Book.page(params[:page])
    authorize @books
  end

  def new
    @book = Book.new
    authorize @book
  end

  def create
    @book = Book.new(book_params)
    authorize @book

    if @book.save
      redirect_to book_url(@book), notice: 'New Book Created'
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    authorize @book
  end

  def edit
    @book = Book.find(params[:id])
    authorize @book
  end

  def update
    @book = Book.find(params[:id])
    authorize @book

    if @book.update(book_params)
      redirect_to book_url(@book), notice: 'Book Updated'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    authorize book

    book.destroy
    redirect_to books_url, notice: 'Book Deleted'
  end

  private

  def book_params
    params.require(:book).permit(:title,
                                 :author,
                                 :isbn,
                                 :quantity)
  end
end

app/views/books/_form.html.erb
<% if form.object.errors[:base].present? %>
  <%= render_flash_message(:alert, form.object.errors[:base].join('\n')) %>
<% end %>

<div class='form-group <%= error_class_for(form.object, :title) %>'>
  <%= form.label :title, class: 'col-sm-2 control-label' %>
  <div class='col-sm-4'>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter Title' %>
    <%= error_messages_for(form.object, :title) %>
  </div>
</div>

<div class='form-group <%= error_class_for(form.object, :author) %>'>
  <%= form.label :author, class: 'col-sm-2 control-label' %>
  <div class='col-sm-4'>
    <%= form.text_field :author, class: 'form-control', placeholder: 'Enter Author Name' %>
    <%= error_messages_for(form.object, :author) %>
  </div>
</div>

<div class='form-group <%= error_class_for(form.object, :isbn) %>'>
  <%= form.label :isbn, class: 'col-sm-2 control-label' %>
  <div class='col-sm-4'>
    <%= form.text_field :isbn, class: 'form-control', placeholder: 'Enter ISBN' %>
    <%= error_messages_for(form.object, :isbn) %>
  </div>
</div>

<div class='form-group <%= error_class_for(form.object, :quantity) %>'>
  <%= form.label :quantity, class: 'col-sm-2 control-label' %>
  <div class='col-sm-4'>
    <%= form.number_field :quantity, class: 'form-control', placeholder: 'Enter Quantity', min: '0' %>
    <%= error_messages_for(form.object, :quantity) %>
  </div>
</div>

app/views/books/edit.html.erb
<% select_nav 'Books' %>

<div id='page_content'>
  <div class='page-header'>
    <h2>
      Edit Book
    </h2>
  </div>

  <div class='page-body'>
    <%= form_for @book, url: book_url(@book), html: {class: 'form-horizontal'} do |f| %>

      <%= render partial: 'form', locals: { form: f, book: @book } %>

      <div class='form-group'>
        <div class='col-sm-offset-2 col-sm-4'>
          <%= f.submit 'Update', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<% select_nav 'Books' %>

<div id='page_content'>
  <div class='page-header'>
    <h2>
      Books
        <% if BookPolicy.new(current_user, @book).new? %>
          <%= link_to 'Add Book', new_book_url, class: 'btn btn-primary pull-right' %>
        <% end %>
    </h2>
  </div>

  <% if @books.present? %>
    <div class='table-responsive'>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Total Copies</th>
            <th>Available Copies</th>
            <th>Updated At</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @books.each_with_index do |book, index| %>
            <tr>
              <td class='index'><%= index+1 %></td>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
              <td><%= book.isbn %></td>
              <td><%= book.quantity %></td>
              <td><%= book.availability %></td>
              <td><%= book.updated_at.to_date_short %></td>
              <td>
                <%= link_to 'View', book_url(book.id) %>
                | <%= link_to 'Edit', edit_book_url(book.id) %>
                | <%= link_to 'Delete', book_url(book.id), method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
           </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <%= paginate @books %>
  <% else %>
    <div class='text-muted'>No Books Found</div>
  <% end %>
</div>

app/views/books/new.html.erb
<% select_nav 'Books' %>

<div id='page_content'>
  <div class='page-header'>
    <h2>
      New Book
    </h2>
  </div>

  <div class='page-body'>
    <%= form_for @book, url: books_url, html: {class: 'form-horizontal'} do |f| %>

      <%= render partial: 'form', locals: { form: f, book: @book } %>

      <div class='form-group'>
        <div class='col-sm-offset-2 col-sm-4'>
          <%= f.submit 'Create', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<% select_nav 'Books' %>

<div id='page_content'>
  <div class='page-header'>
    <h2>
      Book
      <% if BookPolicy.new(current_user, @book).edit? %>
        - <%= link_to 'Edit', edit_book_url(@book) %>
        - <%= link_to 'Allocate', new_book_book_allocation_url(@book) %>
      <% end %>
    </h2>
  </div>

  <div class='page-body'>
    <div class='row'>
      <div class='col-md-6'>
        <strong style='margin-right:10px;'>Title: </strong>
        <%= @book.title %>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-6'>
        <strong style='margin-right:10px;'>Author: </strong>
        <%= @book.author %>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-6'>
        <strong style='margin-right:10px;'>ISBN: </strong>
        <%= @book.isbn %>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-6'>
        <strong style='margin-right:10px;'>Total Copies: </strong>
        <%= @book.quantity %>
      </div>
    </div>

    <div class='row'>
      <div class='col-md-6'>
        <strong style='margin-right:10px;'>Available Copies: </strong>
        <%= @book.availability %>
      </div>
    </div>
  </div>
</div>