config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get 'page/:page', action: :index, on: :collection
  end

  resources :books, concerns: [:paginatable] do
    resources :book_allocations, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    get :logout, on: :collection
  end

  root to: 'books#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BttLibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class='navbar navbar-default navbar-fixed-top'>
    <div class='container-fluid'>
      <div class='navbar-header'>
        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'>
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <a class='navbar-brand' href='<%= root_url %>'>
          Library App
        </a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li>
              <a href="<%= logout_sessions_url %>">Logout</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class='container-fluid'>
    <div class='row'>
      <% if signed_in? %>
        <div class='col-sm-3 col-md-2 sidebar'>
          <ul class='nav nav-sidebar'>
            <%= navigation_link 'Books', books_url %>
          </ul>
        </div>
      <% end %>
      <div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
        <%= flash_messages %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>